### ISSUE TITLE
`try_read` for `TlsStream`

### ISSUE THREAD

**Issue by BratSinot** [tokio-rs/tls#123]
Greetings!

Any way to implement something like `TcpStream::try_read` but for `TlsStream`?
I need to try to read data without waiting for data arriving.

**Comment by LucioFranco** [comment]
Which tls crate are you talking about?

**Comment by BratSinot** [comment]
> Which tls crate are you talking about?

`tokio-rustls`.
But `tokio-native-tls` have same api (`trait AsyncRead + AsyncReadExt`) so question will be same for both of them.

**Comment by djc** [comment]
If you have a `std::task::Context` you can call `AsyncRead::poll_read()` directly, I suppose, and handle `Poll::Pending` appropriately? You might get a `Context` through calling [`poll_fn()`](https://doc.rust-lang.org/std/future/fn.poll_fn.html).

**Comment by djc** [comment]
tokio-rustls has moved to https://github.com/rustls/tokio-rustls. Please reopen your issue there if you're still interested.
