### ISSUE TITLE
Getting UnexpectedEof on read_to_end while the sync version works fine

### ISSUE THREAD

**Issue by lufte** [tokio-rs/tls#141]
I'm having a strange behavior where reading from a server fails with `UnexpectedEof` after reading all bytes while the sync alternative of the same code completes successfully. They all read the exact same bytes. 

I discovered this behavior while writing a browser for [Gemini](https://gemini.circumlunar.space/), and it happens only when connecting to a specific [server](https://git.sr.ht/~sircmpwn/gmnisrv).

I wrote a full example that connects to a host running that server. The sync code can be run with `cargo run --bin sync` and it will connect to the host, request the index document, and print the bytes received. The async version (`cargo run --bin async`) does the same but receives an `UnexpectedEof` after reading all bytes. The code can be cloned from https://git.sr.ht/~lufte/eof-minimal-working-example.

I appreciate any input on this.

**Comment by quininer** [comment]
see https://github.com/tokio-rs/tls/pull/128 and https://github.com/rustls/rustls/issues/1188

**Comment by lufte** [comment]
Thanks, that clarifies it.
