### ISSUE TITLE
TLS error  when try to write payload with size >= 5kb

### ISSUE THREAD

**Issue by amrx101** [tokio-rs/tls#21]
```   typ: Alert,
   version: TLSv1_3,
   payload: Alert(
       AlertMessagePayload {
           level: Fatal,
           description: InternalError,
       },
   ),
}```
```

We get this error when we try to publish package of large size.

Any ideas, what may be wrong here

**Comment by mleonhard** [comment]
Can you please provide a small rust program that hits the error?

**Comment by amrx101** [comment]
For anyone out there, dealing with this issue, it’s the MTU size. Configure MTU size for the tls library in use.
