### ISSUE TITLE
Feature: Implement into_split for TlsStream

### ISSUE THREAD

**Issue by ColinTimBarndt** [tokio-rs/tls#25]
[TlsStream](https://docs.rs/tokio-native-tls/0.1.0/tokio_native_tls/struct.TlsStream.html)s should support splitting them into two separate structs for reading and writing (and re-uniting them again to a TlsStream struct). This is already implemented for TCP streams: [TcpStream::into_split](https://docs.rs/tokio/0.2.22/tokio/net/struct.TcpStream.html#method.into_split)

This feature would be very nice to have when using Tokio with the [Actor Model](https://en.wikipedia.org/wiki/Actor_model). Splitting the stream into halves is necessary in order to have them in separate threads (actors).

**Comment by quininer** [comment]
This requires the TLS library support full duplex, but this can be a bit complicated. Currently you can use [general split implementation](https://docs.rs/tokio/0.2.22/tokio/io/fn.split.html).
