### ISSUE TITLE
Document errors

### ISSUE THREAD

**Issue by mleonhard** [tokio-rs/tls#35]
Let's document the errors returned by [`TlsAcceptor`](https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.TlsAcceptor.html) and [`TlsConnector`](https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.TlsConnector.html).

**Comment by djc** [comment]
tokio-rustls has moved to https://github.com/rustls/tokio-rustls. Please reopen your issue there if you're still interested.
