### ISSUE TITLE
tokio-rustls: bring back writev

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tls#36]
Since Tokio 0.3 removed support for vectored IO, `tokio-rustls` will no longer use `writev` when available (see #29). When tokio-rs/tokio#3135 is resolved, and Tokio re-adds support for vectored IO, it would be great to get writev support back in `tokio-rustls`.

In an ideal world, the solution with the new API in Tokio would no longer require specialization, so vectored IO could be supported on the stable compiler as well.

**Comment by hawkw** [comment]
I'd be happy to work on this, though it is obviously blocked on tokio-rs/tokio#3135.

**Comment by quininer** [comment]
@hawkw  Hi, are you still interested in this?

**Comment by hawkw** [comment]
@quininer yup, just a bit busy with some other things. I'd like to take a look at this in the near future unless anyone beats me to it!
