### ISSUE TITLE
Backport rustls version upgrade as tokio-rustls 0.15.0

### ISSUE THREAD

**Issue by paolobarbolini** [tokio-rs/tls#39]
The lettre crate [supports both tokio 0.2 and tokio 0.3](https://github.com/lettre/lettre/blob/3683d122baaa9bede82ef18baf533da1dacc2655/Cargo.toml#L58-L63). We'd like to support 1.0 too when it comes out, but we can't do so unless the tokio-rustls corresponding to each tokio version we support takes the same rustls version.

Could #37 be backported and released as 0.15.0, making it possible to get rustls 0.19 in tokio 0.2 projects?

**Comment by quininer** [comment]
Okay, I put it in the [tokio-rustls/0.15](https://github.com/tokio-rs/tls/tree/tokio-rustls/0.15) branch.

**Comment by paolobarbolini** [comment]
Thanks!
