### ISSUE TITLE
Derive `Debug` for `tokio_rustls::TlsStream`

### ISSUE THREAD

**Issue by ffuugoo** [tokio-rs/tls#44]
`Debug` is derived for both [`tokio_rustls::client::TlsStream`](https://docs.rs/tokio-rustls/0.21.1/tokio_rustls/client/struct.TlsStream.html#impl-Debug) and [`tokio_rustls::server::TlsStream`](https://docs.rs/tokio-rustls/0.21.1/tokio_rustls/server/struct.TlsStream.html#impl-Debug).

Is there a reason [`tokio_rustls::TlsStream`](https://docs.rs/tokio-rustls/0.21.1/tokio_rustls/enum.TlsStream.html) does not derive `Debug`?

Not much of an issue, of course, but it's a single line fix in the library instead of multiple lines of defining project-internal newtype.

**Comment by quininer** [comment]
No special reason, PR is welcome. :)

**Comment by ffuugoo** [comment]
Done in #45.
