### ISSUE TITLE
rsa_private_keys() returns an empty vector

### ISSUE THREAD

**Issue by OnikenX** [tokio-rs/tls#57]
I found this problem with the rustls::pemfile::rsa_private_keys(), I made some tests and looks like this function returns an empty vector from a buffer created from a private key generated with:
```bash
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout private.key -out certificate.crt
```
To test my problem create an private key with the command above and run this test:
```rust
#[test]
fn test_rsa(){
    let file = std::fs::File::open("private.key").unwrap();
    let rd = &mut std::io::BufReader::new(file);
    let vector = tokio_rustls::rustls::internal::pemfile::rsa_private_keys(rd).unwrap();
    assert!(vector.len() > 0);
}
```
For me at least it fails on having at least 1 member:
```
assertion failed: vector.len() > 0
```

I'm new on this but based on the example I think this shouldn't do this.

**Comment by San-greal** [comment]
yep，me too
![image](https://user-images.githubusercontent.com/25400257/116639775-dc8a2c80-a99b-11eb-8c31-254be780d32a.png)

**Comment by djc** [comment]
That code lives in rustls, so this is not the right repo to file this against. Additionally the best version of this code now lives in the separate [rustls-pemfile](https://crates.io/crates/rustls-pemfile) crate, so please try that.
