### ISSUE TITLE
为什么 server 端的 impl<IO> AsyncWrite for TlsStream<IO> 不进行 `TlsState::WriteShutdown` 等状态的判断呢？

### ISSUE THREAD

**Issue by San-greal** [tokio-rs/tls#60]
![image](https://user-images.githubusercontent.com/25400257/117772712-0b40b680-b26a-11eb-8d00-845ad6885b57.png)
而是这样直接进行 `poll_write` 操作？不是很明白，希望您能讲解一下

**Comment by djc** [comment]
Google Translate:

> Why doesn't `impl<IO> AsyncWrite for TlsStream<IO>` on the server side perform TlsState::WriteShutdown and other state judgments?

Is this related to #58?
