### ISSUE TITLE
Using rustls cargo features?

### ISSUE THREAD

**Issue by realaltffour** [tokio-rs/tls#61]
How would I go by enabling rustls feature "rustls/dangerous_configuration"?

**Comment by djc** [comment]
tokio-rustls also exposes a `dangerous_configuration` feature, so you can enable that. (Beyond that, you can always take on a direct dependency on rustls and enable whatever feature flags you want.)

**Comment by realaltffour** [comment]
Would there be any conflicts if I added rustls as a dependencies directly?

**Comment by sfackler** [comment]
As long as the version of rustls you specify matches with the version this crate specifies, the dependency will be shared and the enabled features will be combined.

**Comment by realaltffour** [comment]
ok, much appreciated!
