### ISSUE TITLE
Cut release with rustls 0.20 support

### ISSUE THREAD

**Issue by edward-shen** [tokio-rs/tls#80]
Hello!

Thanks for your work! I'm trying to orchestrate bumping `actix` to use `rustls` 0.20, and this seems to be a blocking dependency.

I see that there's already work to implement `rustls` 0.20. May I have an update on:
1. If there's any ETA for a version bump for `rustls` 0.20?
2. If not, are there any significant concerns from blocking a release?

I'm just looking to document the progress for my own PRs, so please don't feel the need to rush out a release or anything like that; that's not my intent.

Thanks!
Eddie

**Comment by quininer** [comment]
I created a milestone. see https://github.com/tokio-rs/tls/milestone/1

**Comment by edward-shen** [comment]
Thanks!

**Comment by quininer** [comment]
tokio-rustls 0.23 has been released.
